[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/startup.sh"
healthcheckPath = "/status"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[vars]
ENVIRONMENT = "production"
DEBUG = "0"
