[build]
builder = "nixpacks"
buildCommand = "chmod +x *.py && chmod +x start.sh"

[deploy]
startCommand = "python status_server.py"
healthcheckPath = "/status"
healthcheckTimeout = 60
healthcheckInterval = 15
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
